export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const FETCH_TORRENTS_START = 'FETCH_TORRENTS_START';
export const FETCH_TORRENTS_END = 'FETCH_TORRENTS_END';
export const SET_TOPBAR_DATA = 'SET_TOPBAR_DATA';
export const UPDATE_TORRENTS = 'UPDATE_TORRENTS';
export const SWITCH_AUTO_UPDATE = 'SWITCH_AUTO_UPDATE';
export const CHANGE_PAGE = 'CHANGE_PAGE';